#ifndef X_DECL_BIN_EXPR
#define X_DECL_BIN_EXPR(X) X_DECL_EXPR(X)
#endif

X_DECL_BIN_EXPR(Add)
X_DECL_BIN_EXPR(Sub)
X_DECL_BIN_EXPR(Mul)
X_DECL_BIN_EXPR(Div)
X_DECL_BIN_EXPR(Mod)
X_DECL_BIN_EXPR(FloorDiv)
X_DECL_BIN_EXPR(FloorMod)
X_DECL_BIN_EXPR(Min)
X_DECL_BIN_EXPR(Max)
X_DECL_BIN_EXPR(RightShift)
X_DECL_BIN_EXPR(LeftShift)
X_DECL_BIN_EXPR(And)
X_DECL_BIN_EXPR(Or)
X_DECL_BIN_EXPR(XOr)
X_DECL_BIN_EXPR(BitAnd)
X_DECL_BIN_EXPR(BitOr)
X_DECL_BIN_EXPR(BitXOr)
X_DECL_BIN_EXPR(GT)
X_DECL_BIN_EXPR(GE)
X_DECL_BIN_EXPR(LT)
X_DECL_BIN_EXPR(LE)
X_DECL_BIN_EXPR(EQ)
X_DECL_BIN_EXPR(NE)

#undef X_DECL_BIN_EXPR
