#ifndef X_DECL_EXPR
#define X_DECL_EXPR(x)
#endif

#ifndef X_DECL_EXPR_FINAL
#define X_DECL_EXPR_FINAL(x) X_DECL_EXPR(x)
#endif

X_DECL_EXPR(Expr)
X_DECL_EXPR_FINAL(IfExpr)
X_DECL_EXPR_FINAL(BinOp)
X_DECL_EXPR_FINAL(UnOp)
X_DECL_EXPR_FINAL(Call)
X_DECL_EXPR_FINAL(IntImm)
X_DECL_EXPR_FINAL(FloatImm)
X_DECL_EXPR_FINAL(Var)
