#ifndef X_DECL_EXPR
#define X_DECL_EXPR(X) X_DECL_IR(X)
#endif

X_DECL_EXPR(Expr)
X_DECL_EXPR(IfExpr)
X_DECL_EXPR(BinOp)
X_DECL_EXPR(UnOp)
X_DECL_EXPR(Call)
X_DECL_EXPR(Load)
X_DECL_EXPR(Slice)
X_DECL_EXPR(Const)
X_DECL_EXPR(IntConst)
X_DECL_EXPR(FloatConst)
X_DECL_EXPR(Var)

#undef X_DECL_EXPR
